# Staging Deployment Configuration
# Reduced resources and replicas for staging environment

---
# API Service Deployment - Staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: aquaculture-staging
  labels:
    app: api-service
    tier: backend
    environment: staging
spec:
  replicas: 1  # Single replica for staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        tier: backend
        environment: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: api-service
        image: ghcr.io/saidulislam1602/aquaculture_machine_learning_platform/api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# ML Service Deployment - Staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: aquaculture-staging
  labels:
    app: ml-service
    tier: ml
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
        tier: ml
        environment: staging
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: ml-service
        image: ghcr.io/saidulislam1602/aquaculture_machine_learning_platform/ml-service:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
