# Infrastructure Alerting Rules for Aquaculture ML Platform
groups:
  - name: infrastructure_alerts
    rules:
      # Node/System Alerts
      - alert: HighCPUUsage
        expr: |
          (
            100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
          ) > 80
        for: 5m
        labels:
          severity: warning
          component: infrastructure
          team: platform
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 
            node_memory_MemTotal_bytes
          ) * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: infrastructure
          team: platform
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) /
            node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: infrastructure
          team: platform
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

      - alert: DiskSpaceCritical
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) /
            node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100 > 95
        for: 2m
        labels:
          severity: critical
          component: infrastructure
          team: platform
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

      # Database Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
          team: platform
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgreSQLHighConnections
        expr: |
          (
            pg_stat_database_numbackends / 
            pg_settings_max_connections
          ) * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: database
          team: platform
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL is using {{ $value }}% of available connections"

      - alert: PostgreSQLSlowQueries
        expr: |
          pg_stat_activity_max_tx_duration{datname!~"template.*"} > 300
        for: 2m
        labels:
          severity: warning
          component: database
          team: platform
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Long running query detected ({{ $value }}s) in database {{ $labels.datname }}"

      # Redis Alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          component: cache
          team: platform
        annotations:
          summary: "Redis is down"
          description: "Redis cache server is not responding"

      - alert: RedisHighMemoryUsage
        expr: |
          (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
          component: cache
          team: platform
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}%"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
          component: cache
          team: platform
        annotations:
          summary: "Redis high connection count"
          description: "Redis has {{ $value }} connected clients"

      # Kafka Alerts
      - alert: KafkaDown
        expr: up{job="kafka"} == 0
        for: 1m
        labels:
          severity: critical
          component: messaging
          team: platform
        annotations:
          summary: "Kafka is down"
          description: "Kafka message broker is not responding"

      - alert: KafkaHighLag
        expr: kafka_consumer_lag_sum > 1000
        for: 5m
        labels:
          severity: warning
          component: messaging
          team: platform
        annotations:
          summary: "Kafka consumer lag is high"
          description: "Consumer lag is {{ $value }} messages for topic {{ $labels.topic }}"

      # Container Alerts
      - alert: ContainerHighCPU
        expr: |
          (
            rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100
          ) > 80
        for: 5m
        labels:
          severity: warning
          component: containers
          team: platform
        annotations:
          summary: "Container {{ $labels.name }} high CPU usage"
          description: "Container CPU usage is {{ $value }}%"

      - alert: ContainerHighMemory
        expr: |
          (
            container_memory_usage_bytes{name!=""} / 
            container_spec_memory_limit_bytes{name!=""}
          ) * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: containers
          team: platform
        annotations:
          summary: "Container {{ $labels.name }} high memory usage"
          description: "Container memory usage is {{ $value }}%"

      - alert: ContainerRestarting
        expr: |
          rate(container_start_time_seconds{name!=""}[5m]) > 0
        for: 1m
        labels:
          severity: warning
          component: containers
          team: platform
        annotations:
          summary: "Container {{ $labels.name }} is restarting"
          description: "Container has restarted {{ $value }} times in the last 5 minutes"

      # Network Alerts
      - alert: HighNetworkReceive
        expr: |
          rate(node_network_receive_bytes_total[5m]) * 8 > 100000000  # 100 Mbps
        for: 5m
        labels:
          severity: warning
          component: infrastructure
          team: platform
        annotations:
          summary: "High network receive on {{ $labels.instance }}"
          description: "Network receive is {{ $value | humanize }}bps on interface {{ $labels.device }}"

      - alert: HighNetworkTransmit
        expr: |
          rate(node_network_transmit_bytes_total[5m]) * 8 > 100000000  # 100 Mbps
        for: 5m
        labels:
          severity: warning
          component: infrastructure
          team: platform
        annotations:
          summary: "High network transmit on {{ $labels.instance }}"
          description: "Network transmit is {{ $value | humanize }}bps on interface {{ $labels.device }}"

