# Production Services Configuration

---
# API Service (Blue-Green deployment ready)
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: aquaculture-prod
  labels:
    app: api-service
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api-service
    version: green  # Initially points to green

---
# ML Service
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: aquaculture-prod
  labels:
    app: ml-service
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ml-service
